spring:
  datasource:
    url: jdbc:mysql://rds-mysql-cscd350.cv4g0yucc9qe.us-west-2.rds.amazonaws.com:3306/HealthConnect
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: administrator
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
#server:
#  port: 8080


